### ISSUE TITLE
Questions about categorization of some measurements

### ISSUE THREAD

**Issue by xinyuejohn** [USM-CHU-FGuyon/BlendedICU#19] opened 2024-01-22 14:07 UTC
I've noticed that in the final OMOP tables, some measurements are represented using numerical labels. This includes various Glasgow Coma Scale assessments (total, eye opening, verbal, etc.) which are no longer in literal label form. However, I'm unable to locate the corresponding conversion information or understand what each numerical value represents.

Per the OMOP CDM guidelines, the original verbatim values from the source table should be preserved in the `measurement_source_value` column of the measurement table. Could you please verify this?

Thank you!

**Comment by USM-CHU-FGuyon** [comment] 2024-01-23 06:37
Hi, I'm not sure I get what the issue is, does it apply to other variables than Glasgow Coma Scores ?

Regarding Glasgow Coma Scores, they are numerical scores; values in the OMOP tables should be the same as values from the original datasets.
![content_gcs_(1)](https://github.com/USM-CHU-FGuyon/BlendedICU/assets/104059079/9c4b9eab-9f4f-4a42-831c-3d8b97e8f5a3)
These scores usually are int values but in some cases there are float values. 
Here are the `value_counts` of the first chunk of measurements for the `Glasgow coma score total` (concept id 3007194)
```
value_as_number
14.000000    12412
3.000000      6025
4.000000      5525
6.000000      5250
13.000000     4876
15.000000     4575
5.000000      3958
10.000000     3557
9.000000      3465
7.000000      1826
12.000000     1747
8.000000      1606
11.000000     1242
14.333333        6
13.666667        2
8.500000         2
14.600000        1
3.583333         1
12.666667        1
12.500000        1
13.933333        1
14.500000        1
8.666667         1
14.200000        1
8.333333         1
10.466666        1
9.166667         1
6.933333         1
7.500000         1
4.600000         1
Name: count, dtype: int64
```
Does it look ok for you ? 

Upon verifying the data, I noticed that the subscores (eye, verbal, motor) were missing from the measurement chunk file, this will be fixed in the next patch.

**Comment by xinyuejohn** [comment] 2024-01-23 08:19
Thanks for your prompt reply! This is exactly what I'm asking for.

**Closed** 2024-01-26 09:36 UTC
